### ISSUE TITLE
Connecting to Server with self-signed certificate

### ISSUE THREAD

**Issue by ahk97** [Pmant/ioBroker.mqtt-client#10]
Connection to servers with self signed certificates is not possible.
client error: Error: self signed certificate in certificate chain

Need option to skip certificate checking ("accept all certificates")

**Comment by ahk97** [comment]
So has this been solved?

**Comment by Pmant** [comment]
Upcoming version has an option called _rejectUnauthorized_ which is not exposed in the adapter options. You have to enable expert mode, edit `system.adapter.mqtt-client.0` and set _rejectUnauthorized_ to false.
