### ISSUE TITLE
Add GitHub secrets for automated releases by release script :-)

### ISSUE THREAD

**Issue by Apollon77** [Pmant/ioBroker.mqtt-client#109]
basically add an secret NPM_TOKEN (create on npm an automation token) and to pot allow dependbot auto merges also create a secret AUTO_MERGE_TOKEN (see https://github.com/ioBroker/ioBroker.example/blob/master/JavaScript/.github/workflows/dependabot-auto-merge.yml#L22)

**Comment by Apollon77** [comment]
When we have this also I can simply push new releases by using the release script :-)

**Comment by Pmant** [comment]
Done.

**Comment by Apollon77** [comment]
Cool, thank you!! So I can also release stuff if needed and do not always need Bluefox or your SAupport:-)
