### ISSUE TITLE
Adapter does not work with js-controller 2.0

### ISSUE THREAD

**Issue by algar42** [Pmant/ioBroker.mqtt-client#17]
1. Adapter does not subscribe to states on run - problem is in GetObjectView in main function. Getobjectview does not return value.common, instead the 'common' property returned right in the value.

2. Adapter fails on restart. It can be restarted for some reasons only every second time. On first restart it is terminated - then run - then terminated once again.

**Comment by algar42** [comment]
For #1 - proposed change in the PR

**Comment by Pmant** [comment]
still not working @GermanBluefox ?
https://github.com/Pmant/ioBroker.mqtt-client/pull/18#issuecomment-541937934

**Comment by ConBeeUser** [comment]
for me, publishing works (it directly transmits sensor data from deconz objects) 
but it **won't react on subscriptions**.
The changed mqtt value is fired correctly and the object is set up as it was in the past.

I updated to the js-controller 2.0 compatible version (1.2.0).

I also still have the restarting bug:


mqtt-client.0 | 2019-10-16 20:16:52.607 | info | (31701) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
-- | -- | -- | --
mqtt-client.0 | 2019-10-16 20:16:45.841 | info | (31701) connected to broker

**Comment by algar42** [comment]
Please try to install version from this repo 
  https://github.com/algar42/ioBroker.mqtt-client
and let me know if it works Ok in your installation

**Comment by ConBeeUser** [comment]
> Please try to install version from this repo
> https://github.com/algar42/ioBroker.mqtt-client
> and let me know if it works Ok in your installation

May I install this adapter side-by-side to the original adapter?

**Comment by algar42** [comment]
hmm... no, if I understood you correctly.  This is same same adapter... the version in the link is just with updated code that works for me and couple of others with js-controller 2.0

**Comment by ConBeeUser** [comment]
Thank you @algar42!
I just installed it over the existing one simply by installing from github.
I thought, that might bring in another adapter-instance but iobroker directly saw it as an update. :-)

But to my astonishment, version 1.1.1 got installed? It already was on v1.2.0?

BUT: Now it works again! Awesome! Thank You!

**Comment by Pmant** [comment]
@algar42 May I ask if you could prepare a PR that is based on the current master? The current PR removes and adds a lot code and jumps back to 1.1.1.

**Comment by algar42** [comment]
May I ask you, why you merged completely not working version to master without any testing and any feedback and made it available to all? 
Answering your question - no, I can't. The code was almost completely re-written and I'm not going to do this one more time, sorry. 
The code that I have is not the "back to 1.1.1", but the mix of what was done by bluefox in #19 and my update that I made for myself. 
It is your choice accept my version, or to write yet another, but working, one.

**Comment by Pmant** [comment]
I am sorry if you feel offended by my request. As a matter of fact I can't simply merge your PR because it has conflicts. 
@GermanBluefox how should I proceed with this adapter? It's not working right now and I currently do not have the time to dig into 2.0.

**Comment by algar42** [comment]
@Pmant you could replace only main.js, io-package.json and package.json from my copy. and it should work. 
You could do this manually in your master if merge does not work.
Please try and let me know. 
if does not help, I'll try to clone current master and do update.

**Comment by Pmant** [comment]
Thank you a lot, I will merge and publish your PR since the current version is not working anyway.

**Comment by algar42** [comment]
Ok. Cool. Closing this issue for now.
