### ISSUE TITLE
Can't send command to channel xiaomi socket

### ISSUE THREAD

**Issue by bogdaan2001** [Pmant/ioBroker.mqtt-client#23]
Hello I connected the xiaomi outlet through mqtt-client, but I can not control it through the script. Please tell me how to do it.  
I try to execute code hrough a JavaScript script 
`sendTo("mqtt.0", "sendMessage2Client", {topic: "zigbee2mqtt/0x00158d0003934947/set", message:" OFF"}); `
and it does not work or I try to do the same thing through blockly, which also does not work
```
sendTo("mqtt.0", "sendMessage2Client", {topic: "zigbee2mqtt/0x00158d0003934947", message: "OFF"});
console.debug("mqtt.0: " + "");
```

<img width="529" alt="Снимок экрана 2019-12-18 в 00 44 04" src="https://user-images.githubusercontent.com/50640169/71036887-98441680-212f-11ea-9846-67f26776de1f.png">
<img width="1022" alt="Снимок экрана 2019-12-18 в 00 44 25" src="https://user-images.githubusercontent.com/50640169/71036894-a134e800-212f-11ea-907c-fd45de2aff77.png">

**Comment by bogdaan2001** [comment]
when i send command ( ON or OFF ) via "mqtt explorer" the socket change status correctly....
how can I achieve the same result from mqtt-client ???

<img width="1012" alt="Снимок экрана 2019-12-18 в 00 52 06" src="https://user-images.githubusercontent.com/50640169/71037453-b9f1cd80-2130-11ea-9473-e3f972254577.png">

**Comment by hartwigm** [comment]
i have the same problem!

Do you have a solution right now?

**Comment by Pmant** [comment]
This issue seems to be related to https://github.com/ioBroker/ioBroker.mqtt
