### ISSUE TITLE
Cannot find view "custom" for search "state" : null

### ISSUE THREAD

**Issue by bogdaan2001** [Pmant/ioBroker.mqtt-client#24]
Hi, what's mean error:

mqtt-client.8 |  error | (15973) Cannot find view "custom" for search "state" : null

version of js-controller 2.1.0
version of mqtt-client 1.2.1

**Comment by itProfi** [comment]
Hi? same problem:

**Comment by GermanBluefox** [comment]
You can install some adapter, e.g. history and it will create custom view. Then the adapter could be removed

**Comment by itProfi** [comment]
Yes, with this PR it's work!
