### ISSUE TITLE
Subscription failed after restart iobroker

### ISSUE THREAD

**Issue by MarkusKress** [Pmant/ioBroker.mqtt-client#25]
When restarting the iobroker, the subscriped vales are not updated anymore. MQTT Broker is mosquitto on the same system. Mosquitto logs:

1578241603: New connection from 192.168.201.253 on port 1883.
1578241603: New client connected from 192.168.201.253 as iobroker_server2 (c1, k60, u'').
1578241603: No will message specified.
1578241603: Sending CONNACK to iobroker_server2 (0, 0)
1578241603: Received SUBSCRIBE from iobroker_server2
1578241603:     vitodens/brennerstd (QoS 0)
1578241603: iobroker_server2 0 vitodens/brennerstd
1578241603: Invalid subscription string from 192.168.201.253, disconnecting.
1578241603: Socket error on client iobroker_server2, disconnecting.

The MQTT-Client adapter is still running/green. After restarting MQTT-Client, the subscription works:

1578241653: New connection from 192.168.201.253 on port 1883.
1578241653: New client connected from 192.168.201.253 as iobroker_server2 (c1, k60, u'').
1578241653: No will message specified.
1578241653: Sending CONNACK to iobroker_server2 (0, 0)
1578241653: Received SUBSCRIBE from iobroker_server2
1578241653:     vitodens/brennerstd (QoS 0)
1578241653: iobroker_server2 0 vitodens/brennerstd
1578241653: Sending SUBACK to iobroker_server2
1578241653: Sending PUBLISH to iobroker_server2 (d0, q0, r1, m0, 'vitodens/brennerstd', ... (8 bytes))

My MQTT-Client setting is: 
MQTT Broker IP an Port, Client ID and Additional subscriptions (vitodens/brennerstd).
The MQTT-Client/Server Adpater works.

I'm using Mosquitto 1.6.8 (newest from git) on Debian Buster.

**Comment by Pmant** [comment]
Should be resolved in upcoming version. Open again if issue persists.
