### ISSUE TITLE
Problem if change Topic

### ISSUE THREAD

**Issue by hartwigm** [Pmant/ioBroker.mqtt-client#27]
i use the mqtt-client in 2 ways 
1.) without modification of the topic
2.) with modification of the topic in the form edomi/set/internal/12345

the number 12345 is a example for a lot of different numbers. 

Example 1 always works without a problem.

Example 2 works only for some days. After this, the mqtt-client, does not publish any Topic

The only solution is so disable the publishing, then the Topic gets his old name. 
After changing the topic to edomi/set/internal/12345 and enable publishing, the story starts for the begining, and works again for some days.

**Comment by F-Plass** [comment]
I have the same problem in the same environment.

**Comment by Pmant** [comment]
Should be resolved in upcoming version. Open again if issue persists.
