### ISSUE TITLE
Allow GitHub Access to continue development or shift in adapter Community?

### ISSUE THREAD

**Issue by Apollon77** [Pmant/ioBroker.mqtt-client#32]
Hi @Pmant,

Könntest Du dir vorstellen Bluefox und mit ggf GitHub Access zu geben oder deine Adapter, wenn du gerade keine Zeit hast, in die Adapter-Community zu schieben? So können wir den Adapter sauber weiterentwickeln.

**Comment by Pmant** [comment]
@Apollon77 habe tatsächlich im Moment keine Zeit für die Adapter, ich schieb sie gerne rüber.

**Comment by Apollon77** [comment]
... oder gib BF und mit GitHub access ... as you like
