### ISSUE TITLE
Subscribing does not work for me with v1.3.0

### ISSUE THREAD

**Issue by steff75** [Pmant/ioBroker.mqtt-client#33]
After updating the adapter from 1.2.1 to 1.3.0, updating new values for subscribed topics no longer works for me. Restarting the adapter and ioBroker in general does not help.

Acknowledgement of values is disabled, as it worked for me with v1.2.1.

After downgrading the adapter from 1.3.0 to 1.2.1 the subscriptions work again and values are taken over by the MQTT Broker.

**Comment by Karatekid2407** [comment]
Same on my side

**Comment by Apollon77** [comment]
Hm ... What mqtt server version is in use?

The adapter has upgraded mqtt library ... I can only refer to https://www.npmjs.com/package/mqtt#notes for now ...  question is of this is relevant for your error cases

**Comment by steff75** [comment]
I use eclipse-mosquitto:latest Docker container with default settings as MQTT server. Last updated 2 weeks ago.

**Comment by GermanBluefox** [comment]
What the use case is here?
- mqtt-client => mqtt-server
or
- mqtt-server => mqtt-client?

**Comment by GermanBluefox** [comment]
Please test 1.3.1

**Comment by steff75** [comment]
1.3.1 is working for me.
The use case with the issue was mqtt-server => mqtt-client, but I use both ways.

Thank you!
