### ISSUE TITLE
prefix for subscribing topics is added to additional subscriptions

### ISSUE THREAD

**Issue by PLCHome** [Pmant/ioBroker.mqtt-client#35]
if I add "additional subscriptions" the "prefix for subscribing topics" is always added.

Actually, I wanted all ioBroker objects to start with the prefix.

Unfortunately I can not subscribe to the "ebus/#" topic now because the module is subscriping "iobroker/set/ebus/#" now.

Only when I delete "Prefix for subscribing topics" do I get the "ebus/#" topic

I think it is wrong.

![image](https://user-images.githubusercontent.com/29116097/78189248-f93ef280-7471-11ea-8d35-57426c080731.png)

![image](https://user-images.githubusercontent.com/29116097/78190725-d7933a80-7474-11ea-8f04-76724ecbfe39.png)

![image](https://user-images.githubusercontent.com/29116097/78190804-001b3480-7475-11ea-91a1-dcdc10bf4cbb.png)

**Comment by stundenblume** [comment]
Same for me!
Would be nice if the "subscribe prefix" would be added to "subscriptions"

@PLCHome
If I read the documentation correct, you can remove the "additional subscriptions" after all objects are created.

> Received messages are converted to states within the adapters namespace (e.g. mqtt.0) and subscribed.
> You can remove topics after all states have been created.

**Comment by PLCHome** [comment]
Due to the amount of information, the MQTT client would actually like to have it generated. 
I'm going to sit down and program this. I think a checkbox below the input, use prefix for subscriptions would be practical. 
I would also switch it on after the update so that the MQTT client behaves exactly as before. 
I hope somebody will merge when I make a request.

**Comment by stundenblume** [comment]
> I'm going to sit down and program this. I think a checkbox below the input, use prefix for subscriptions would be practical.

I would appreciate that!

**Comment by PLCHome** [comment]
> I'm going to sit down and program this. I think a checkbox below the input, use prefix for subscriptions would be practical.

@stundenblume: done

**Comment by stundenblume** [comment]
@PLCHome: Nice! Thank you very much!

**Comment by PLCHome** [comment]
I temporarily solved the problem with a second instance.
for this I deactivated all objects, established a second connection to the mosquito and gave no prefix.

**Comment by PLCHome** [comment]
It is no longer necessary, I no longer use the adapter.
