### ISSUE TITLE
TypeError: val.replace is not a function at MqttClient.stringToVal

### ISSUE THREAD

**Issue by QuoxelNet** [Pmant/ioBroker.mqtt-client#39]
The MQTT Client adapter logs the following text, afterwards it stops and tries to restart:
TypeError: val.replace is not a function at MqttClient.stringToVal (/opt/iobroker/node_modules/iobroker.mqtt-client/main.js:306:14) at getForeignState
uncaught exception: val.replace is not a function

It is caused by the code in line 308 of main.js
With the following addition, the adapter doesn't exit any more: 
`if (val === Object) val = val.replace(',', '.');`

**Comment by Apollon77** [comment]
fixed in next version
