### ISSUE TITLE
Mqtt.Client geht nur sporadisch online 

### ISSUE THREAD

**Issue by sven-s-ter** [Pmant/ioBroker.mqtt-client#41]
Der .Client Adapter geht nach Installation, und korrekter Konfiguration, nur sporadisch-manchmal gar nicht- mit dem Broker (Mosquitto) online. Meist bleibt er auf gelb stehen trotz korrekter Konfiguration. Trotz mehrfacher Neuinstallation und neu aufsetzen des System ist das Verhalten so. 
auch testconnections zu den offiziellen Internetseiten von mqtt oder anderen Brokern schlagen fehl. 

Mqtt.client 1.3.1
Nodejs 12.20
Admin 14.12
Raspi 5.4

**Comment by Apollon77** [comment]
Hast Du Log Ausgaben?

**Comment by sven-s-ter** [comment]
mqtt-client.0 2020-10-20 11:58:45.448 info (3190) trying to reconnect to broker
mqtt-client.0 2020-10-20 11:58:15.446 warn (3190) client offline
mqtt-client.0 2020-10-20 11:58:15.334 info (3190) Try to connect to mqtt://michael:*******************@localhost:1883?clientId=ioBroker
mqtt-client.0 2020-10-20 11:58:15.310 warn (3190) adapter.objects.getObjectView is deprecated, and will be removed in the future. Please use adapter.getObjectView/Async. Report this to Developer!
mqtt-client.0 2020-10-20 11:58:15.269 info (3190) starting. Version 1.3.1 in /opt/iobroker/node_modules/iobroker.mqtt-client, node: v12.19.0, js-controller: 3.1.6

Dies war mit 12.19.0 - selbes Verhalten mit 12.20
