### ISSUE TITLE
Small title error in custom_m

### ISSUE THREAD

**Issue by GermanBluefox** [Pmant/ioBroker.mqtt-client#6]
Here should be qos and not retain:

https://github.com/Pmant/ioBroker.mqtt-client/blob/master/admin/custom_m.html#L72

I know it is my fault.

**Comment by Pmant** [comment]
can you tell me how to deal with this:
http://forum.iobroker.net/viewtopic.php?f=24&t=10268&start=20#p119738

If we can solve this error I'll prepare a new version.

**Comment by GermanBluefox** [comment]
http://forum.iobroker.net/viewtopic.php?f=24&t=10268&p=119779#p119779

**Comment by Pmant** [comment]
thanks.
fixed, commited and published

**Comment by GermanBluefox** [comment]
:+1:
